import numpy as np
import matplotlib.pylab as plt

Piso1t = np.genfromtxt('3_Piso1.dat',delimiter=',')
Piso1 = np.transpose(Piso1t)
Piso2t = np.genfromtxt('3_Piso2.dat',delimiter=',')
Piso2 = np.transpose(Piso2t)
Piso3t = np.genfromtxt('3_Piso3.dat',delimiter=',')
Piso3 = np.transpose(Piso3t)

plt.figure()
plt.title("Primer intento de la trayectoria del edificio")
plt.plot(Piso1[0],Piso1[1], label='Piso 1')
plt.plot(Piso2[0],Piso2[1], label='Piso 2')
plt.plot(Piso3[0],Piso3[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_PrimerEdificio.pdf')

MPiso1t = np.genfromtxt('3_MaximoP1.dat',delimiter=',')
MPiso1 = np.transpose(MPiso1t)
MPiso2t = np.genfromtxt('3_MaximoP2.dat',delimiter=',')
MPiso2 = np.transpose(MPiso2t)
MPiso3t = np.genfromtxt('3_MaximoP3.dat',delimiter=',')
MPiso3 = np.transpose(MPiso3t)

plt.figure()
plt.title("Amplitud maxima en funcion de $\omega$")
plt.plot(MPiso1[0],MPiso1[1], label='Piso 1')
plt.plot(MPiso2[0],MPiso2[1], label='Piso 2')
plt.plot(MPiso3[0],MPiso3[1], label='Piso 3')
plt.legend()
plt.xlabel('$\omega$') 
plt.ylabel('$u_{max}$')
plt.savefig('3_Maximos.pdf')

print('La amplitud maxima tiene maximos locales - en los tres pisos - en las frecuencias: ')
omega_1 = MPiso1[0,np.argmax(MPiso1[1,MPiso1[0]<1])]
print('omega_1=',omega_1, ', indice=', np.argmax(MPiso1[1,MPiso1[0]<1]))
omega_2 = MPiso1[0,np.argmax(MPiso1[1,np.logical_and(MPiso1[0]>1,MPiso1[0]<2)])+MPiso1[1,MPiso1[0]<1].size]
print('omega_2=',omega_2, ', indice=', np.argmax(MPiso1[1,np.logical_and(MPiso1[0]>1,MPiso1[0]<2)])+MPiso1[1,MPiso1[0]<1].size)
omega_3 = MPiso1[0,np.argmax(MPiso1[1,MPiso1[0]>2])+MPiso1[1,MPiso1[0]<2].size]
print('omega_3=',omega_3, ', indice=', np.argmax(MPiso1[1,MPiso1[0]>2])+MPiso1[1,MPiso1[0]<2].size)

Piso1_1t = np.genfromtxt('3_Piso1_omega1.dat',delimiter=',')
Piso1_1 = np.transpose(Piso1_1t)
Piso2_1t = np.genfromtxt('3_Piso2_omega1.dat',delimiter=',')
Piso2_1 = np.transpose(Piso2_1t)
Piso3_1t = np.genfromtxt('3_Piso3_omega1.dat',delimiter=',')
Piso3_1 = np.transpose(Piso3_1t)

plt.figure()
plt.title("Trayectoria del edificio para $\omega_1$="+str(omega_1))
plt.plot(Piso1_1[0],Piso1_1[1], label='Piso 1')
plt.plot(Piso2_1[0],Piso2_1[1], label='Piso 2')
plt.plot(Piso3_1[0],Piso3_1[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_Edificio_omega1.pdf')

Piso1_2t = np.genfromtxt('3_Piso1_omega2.dat',delimiter=',')
Piso1_2 = np.transpose(Piso1_2t)
Piso2_2t = np.genfromtxt('3_Piso2_omega2.dat',delimiter=',')
Piso2_2 = np.transpose(Piso2_2t)
Piso3_2t = np.genfromtxt('3_Piso3_omega2.dat',delimiter=',')
Piso3_2 = np.transpose(Piso3_2t)

plt.figure()
plt.title("Trayectoria del edificio para $\omega_2$="+str(omega_2))
plt.plot(Piso1_2[0],Piso1_2[1], label='Piso 1')
plt.plot(Piso2_2[0],Piso2_2[1], label='Piso 2')
plt.plot(Piso3_2[0],Piso3_2[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_Edificio_omega2.pdf')

Piso1_3t = np.genfromtxt('3_Piso1_omega3.dat',delimiter=',')
Piso1_3 = np.transpose(Piso1_3t)
Piso2_3t = np.genfromtxt('3_Piso2_omega3.dat',delimiter=',')
Piso2_3 = np.transpose(Piso2_3t)
Piso3_3t = np.genfromtxt('3_Piso3_omega3.dat',delimiter=',')
Piso3_3 = np.transpose(Piso3_3t)

plt.figure()
plt.title("Trayectoria del edificio para $\omega_3$="+str(omega_3))
plt.plot(Piso1_3[0],Piso1_3[1], label='Piso 1')
plt.plot(Piso2_3[0],Piso2_3[1], label='Piso 2')
plt.plot(Piso3_3[0],Piso3_3[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_Edificio_omega3.pdf')

Piso1bt = np.genfromtxt('3_Piso1_bono.dat',delimiter=',')
Piso1b = np.transpose(Piso1bt)
Piso2bt = np.genfromtxt('3_Piso2_bono.dat',delimiter=',')
Piso2b = np.transpose(Piso2bt)
Piso3bt = np.genfromtxt('3_Piso3_bono.dat',delimiter=',')
Piso3b = np.transpose(Piso3bt)

plt.figure()
plt.title("Trayectoria con fricción $\gamma =10$, backwards difference")
plt.plot(Piso1b[0],Piso1b[1], label='Piso 1')
plt.plot(Piso2b[0],Piso2b[1], label='Piso 2')
plt.plot(Piso3b[0],Piso3b[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_Edificio_bono.pdf')

Piso1b1t = np.genfromtxt('3_Piso1_bono1.dat',delimiter=',')
Piso1b1 = np.transpose(Piso1b1t)
Piso2b1t = np.genfromtxt('3_Piso2_bono1.dat',delimiter=',')
Piso2b1 = np.transpose(Piso2b1t)
Piso3b1t = np.genfromtxt('3_Piso3_bono1.dat',delimiter=',')
Piso3b1 = np.transpose(Piso3b1t)

plt.figure()
plt.title("Trayectoria con fricción $\gamma =10$, velocidad anterior")
plt.plot(Piso1b1[0],Piso1b1[1], label='Piso 1')
plt.plot(Piso2b1[0],Piso2b1[1], label='Piso 2')
plt.plot(Piso3b1[0],Piso3b1[1], label='Piso 3')
plt.legend()
plt.xlabel('$t$')
plt.ylabel('$u(t)$')
plt.savefig('3_Edificio_bono1.pdf')



